#!/usr/bin/env python3
"""Render the screenshots used in the README.

Everything here runs on **invented data**. That is not squeamishness: the
panels this server normally draws are somebody's actual calendar, and a
screenshot of a real Tuesday is a screenshot of where they will be on Tuesday.
The sample events, teams and readings below are made up, so the gallery can be
regenerated by anyone without leaking anything.

The teams are invented too, and their crests are drawn here rather than
fetched. Real ones come from ESPN at runtime and are nobody's to redistribute;
a repository that ships them is a repository shipping other people's marks.

    python tools/screenshots.py
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from glance.canvas import Canvas  # noqa: E402
from glance.config import load_settings  # noqa: E402
from glance.runtime import GlanceApp  # noqa: E402
from glance.scenes import REGISTRY  # noqa: E402
from glance.sources.ics import Event  # noqa: E402
from glance.sources.scores import FINAL, PRE, Board, Fixture, Side  # noqa: E402
from glance.sources.weather import DayForecast, Weather  # noqa: E402

OUT = ROOT / "docs" / "images"
TZ = ZoneInfo("America/Los_Angeles")
WHEN = datetime(2026, 6, 18, 20, 40, tzinfo=TZ)     # a summer evening
SCALE = 4


# --- stand-ins --------------------------------------------------------------

class FakeWeather:
    configured, last_error = True, None

    def __init__(self, reading): self._r = reading

    def current(self): return self._r


class FakeCalendars:
    def __init__(self, events): self._e = events
    def __bool__(self): return True
    def upcoming(self, now, names=None, lookahead_days=14, include_current=True,
                 include_hidden=False):
        return sorted(self._e, key=lambda e: e.start)


class FakeSource:
    """A scoreboard of invented teams."""

    name, last_error, configured = "sample", None, True

    def __init__(self, fixtures, teams): self._f, self.teams = fixtures, teams

    def fixtures(self, now): return self._f


def event(days, hour, minute, title, all_day=False):
    start = WHEN.replace(hour=hour, minute=minute, second=0,
                         microsecond=0) + timedelta(days=days)
    return Event(summary=title, start=start, end=start + timedelta(hours=1),
                 all_day=all_day, raw_summary=title)


def reading(**kw):
    base = dict(temperature=64, feels_like=62, high=71, low=52,
                condition="clear", is_day=False, unit="F", precip_chance=8,
                aqi=41,
                sunrise=WHEN.replace(hour=5, minute=12),
                sunset=WHEN.replace(hour=21, minute=6),
                forecast=[DayForecast("2026-06-19", "clear", 74, 55),
                          DayForecast("2026-06-20", "partly", 69, 54),
                          DayForecast("2026-06-21", "rain", 63, 51)])
    base.update(kw)
    return Weather(**base)


def crest(colour, mark) -> Image.Image:
    """A stand-in crest: a roundel with a letter in it."""
    size = 14
    art = Canvas(width=16)
    art.disc(7, 7, 6, colour)
    art.text(7, 4, mark, "black", "3x5", "center")
    return art.image.crop((0, 0, size, size))


def side(abbrev, name, score=None, colour="white", **kw):
    return Side(abbrev=abbrev, name=name, score=score, key=abbrev.lower(),
                logo=("sample",), **kw)


# --- the gallery ------------------------------------------------------------

def gallery(app: GlanceApp):
    """(filename, caption, canvas) for each shot."""
    def ctx(**over):
        c = app.context(WHEN, brightness=1.0)
        for k, v in over.items():
            setattr(c, k, v)
        return c

    agenda = [
        event(0, 9, 30, "Standup"),
        event(0, 13, 0, "Dentist"),
        event(0, 17, 30, "Grange meeting"),
        event(1, 8, 15, "Seed order arrives"),
        event(1, 11, 0, "Call the co-op"),
        event(2, 10, 0, "Hive inspection"),
        event(2, 19, 0, "Film night"),
    ]

    shots = []

    shots.append(("sky", "`sky` — the day as an arc, with the real weather on it",
                  REGISTRY["sky"].render(ctx(weather=FakeWeather(reading())), {})))

    shots.append(("columns", "`columns` — three days of calendar, packed to fit",
                  REGISTRY["columns"].render(ctx(calendars=FakeCalendars(agenda)),
                                             {"calendar": "agenda"})))

    shots.append(("weather", "`weather` — now, today's range, and three days out",
                  REGISTRY["weather"].render(
                      ctx(weather=FakeWeather(reading(is_day=True, temperature=71,
                                                      condition="partly"))), {})))

    # An invented league, so no real team's mark is redistributed here.
    class Crests:
        size = 14
        def get(self, key, urls, size=None):
            return {"hrv": crest("mint", "H"), "kes": crest("red", "K"),
                    "ald": crest("sky", "A")}.get(key)

    last = Fixture(away=side("HRV", "Harvesters", 4), home=side("KES", "Kestrels", 6),
                   state=FINAL, start=WHEN - timedelta(days=1), following="HRV")
    last.home.winner = True
    nxt = Fixture(away=side("HRV", "Harvesters"), home=side("ALD", "Alders"),
                  state=PRE, start=(WHEN + timedelta(days=1)).replace(hour=19, minute=5),
                  broadcast="LEAGUE.TV", following="HRV")
    # The board label is drawn at eight characters, so pick one that fits.
    board = Board(name="league", source=FakeSource([last, nxt], ["HRV"]), label="LEAGUE")
    shots.append(("scores", "`scores` — the last result and the next fixture, with crests",
                  REGISTRY["scores"].render(
                      ctx(scoreboards={"league": board}, logos=Crests()),
                      {"board": "league", "accent": "sky"})))

    shots.append(("language", "`language` — a word at a time, accents and all",
                  REGISTRY["language"].render(ctx(), {"language": "es", "label": True,
                                                      "feminine_color": "pink"})))

    shots.append(("banner", "`banner` — a title card, for when the house has visitors",
                  REGISTRY["banner"].render(ctx(), {"title": "WELCOME",
                                                    "subtitle": "COME ON IN",
                                                    "accent": "mint"})))

    shots.append(("agenda", "`agenda` — the next thing, large",
                  REGISTRY["agenda"].render(ctx(calendars=FakeCalendars(agenda)),
                                            {"calendar": "agenda", "count": 1})))

    shots.append(("sprite", "`sprite` — pixel art set into a line of text",
                  REGISTRY["sprite"].render(ctx(), {"before": "It's", "after": "season!"})))

    return shots


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    app = GlanceApp(load_settings())
    shots = gallery(app)

    lines = []
    for name, caption, canvas in shots:
        path = OUT / f"{name}.png"
        canvas.scaled(SCALE).save(path)
        lines.append(f"{caption}\n\n![{name}](docs/images/{name}.png)\n")
        print(f"  wrote {path.relative_to(ROOT)}")

    strip = Image.new("RGB", (192 * SCALE, (32 + 3) * SCALE * len(shots)), (8, 8, 10))
    for index, (_, _, canvas) in enumerate(shots):
        strip.paste(canvas.scaled(SCALE), (0, index * (32 + 3) * SCALE))
    strip.save(OUT / "gallery.png")
    print(f"  wrote {(OUT / 'gallery.png').relative_to(ROOT)}")

    (OUT / "GALLERY.md").write_text(
        "<!-- generated by tools/screenshots.py -->\n\n" + "\n".join(lines),
        encoding="utf-8")
    print(f"  wrote {(OUT / 'GALLERY.md').relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
